'use client';
import { useEffect, useState } from 'react';
export default function Admin(){const [key,setKey]=useState('');const [data,setData]=useState<any>({batches:[],passports:[]});const [batch,setBatch]=useState({year:'2026',batchName:'Batch A',stream:'Stream 2',platoon:'Platoon 9',description:'',status:'active'});const [active,setActive]=useState('');const [settings,setSettings]=useState({maxEditsPerIp:3,cooldownMinutes:30,allowRawPhotoClaim:true,requireAdminApproval:true});const [file,setFile]=useState<File|null>(null);const [msg,setMsg]=useState('');
async function load(){const r=await fetch('/api/admin/batches?adminKey='+key);setData(await r.json())} useEffect(()=>{if(key)load()},[key]);
async function createBatch(e:any){e.preventDefault();await fetch('/api/admin/batches',{method:'POST',headers:{'Content-Type':'application/json','x-admin-key':key},body:JSON.stringify(batch)});load()}
async function upload(e:any){e.preventDefault();if(!file||!active)return;const fd=new FormData();fd.append('zip',file);fd.append('batchId',active);const r=await fetch('/api/admin/upload',{method:'POST',headers:{'x-admin-key':key},body:fd});setMsg(JSON.stringify(await r.json()));load()}
async function saveSettings(){await fetch('/api/admin/settings',{method:'POST',headers:{'Content-Type':'application/json','x-admin-key':key},body:JSON.stringify({batchId:active,settings})});setMsg('Settings saved')}
async function approve(id:string){await fetch('/api/admin/approve',{method:'POST',headers:{'Content-Type':'application/json','x-admin-key':key},body:JSON.stringify({id})});load()}
return <main className="max-w-6xl mx-auto p-5"><section className="card p-6 mt-8"><h1 className="text-2xl font-black">Admin Panel</h1><input className="mt-3" value={key} onChange={e=>setKey(e.target.value)} placeholder="Enter ADMIN_KEY"/></section><section className="grid md:grid-cols-2 gap-5 mt-5"><form onSubmit={createBatch} className="card p-6"><h2 className="font-black text-xl">Create Year / Batch / Stream</h2>{['year','batchName','stream','platoon','description'].map(k=><input key={k} className="mt-2" value={(batch as any)[k]} onChange={e=>setBatch({...batch,[k]:e.target.value})} placeholder={k}/>)}<select className="mt-2" value={batch.status} onChange={e=>setBatch({...batch,status:e.target.value})}><option>active</option><option>closed</option><option>archived</option></select><button className="btn mt-3">Create Batch</button></form><form onSubmit={upload} className="card p-6"><h2 className="font-black text-xl">Upload Passport ZIP</h2><select className="mt-2" value={active} onChange={e=>setActive(e.target.value)}><option value="">Select batch</option>{data.batches?.map((b:any)=><option value={b.id} key={b.id}>{b.year} {b.batchName} {b.stream} {b.platoon}</option>)}</select><input className="mt-2" type="file" accept=".zip" onChange={e=>setFile(e.target.files?.[0]||null)}/><button className="btn mt-3">Upload ZIP</button><button type="button" onClick={()=>window.location.href='/api/admin/download-all?adminKey='+key+'&batchId='+active} className="btn2 mt-3 ml-2">Download Bulk ZIP</button></form></section><section className="card p-6 mt-5"><h2 className="font-black text-xl">Cooldown Settings</h2><div className="grid md:grid-cols-4 gap-3 mt-3"><input type="number" value={settings.maxEditsPerIp} onChange={e=>setSettings({...settings,maxEditsPerIp:+e.target.value})}/><input type="number" value={settings.cooldownMinutes} onChange={e=>setSettings({...settings,cooldownMinutes:+e.target.value})}/><label><input type="checkbox" checked={settings.allowRawPhotoClaim} onChange={e=>setSettings({...settings,allowRawPhotoClaim:e.target.checked})}/> Allow raw claim</label><label><input type="checkbox" checked={settings.requireAdminApproval} onChange={e=>setSettings({...settings,requireAdminApproval:e.target.checked})}/> Require approval</label></div><button onClick={saveSettings} className="btn mt-3">Save Settings</button></section>{msg&&<pre className="card p-4 mt-4 whitespace-pre-wrap">{msg}</pre>}<section className="card p-6 mt-5 overflow-auto"><h2 className="font-black text-xl">Passports</h2><table className="w-full text-sm mt-3"><tbody>{data.passports?.map((p:any)=><tr className="border-t" key={p.id}><td><img src={p.imageUrl} className="w-16 h-16 object-cover"/></td><td>{p.name||'UNASSIGNED'}<br/>{p.originalFilename}</td><td>{p.stateCode}</td><td>{p.fileNumber}</td><td>{p.phone}</td><td>{p.status}</td><td><button onClick={()=>approve(p.id)} className="btn2">Approve</button></td></tr>)}</tbody></table></section></main>}
